### ISSUE TITLE
About required plugins

### ISSUE THREAD

**Issue by gihanrangana** [kristiandz/ebc-pm#2]
Nice work.
Could you please add the required plugins and server.cfg to the repo?

**Comment by kristiandz** [comment]
[gsclib.zip](https://github.com/kristiandz/ebc-pm/files/8642380/gsclib.zip)

**Comment by gihanrangana** [comment]
i have getting this error when i try to build
![image](https://user-images.githubusercontent.com/24897554/167243379-90f8663c-e0f0-4a49-ae33-30ff806bb264.png)

**Comment by kristiandz** [comment]
You can build the plugin without CGSC if you take an older version of the gsclib repo, I see that it got updated, and its now using cmake, so you will need to request support from iswen, not me.

**Comment by kristiandz** [comment]
GSCLIB plugin was updated on this mod to version 4f91e4dc52fd802f2fde8fdc81a2194bc81ee466, this commit id matches gsclib repo.

Code will be pushed soon.
