### ISSUE TITLE
Error when map getting change

### ISSUE THREAD

**Issue by gihanrangana** [kristiandz/ebc-pm#3]
what is that error?
![image](https://user-images.githubusercontent.com/24897554/169478729-13cf38af-f203-4230-a352-c8d447f16754.png)

**Comment by gihanrangana** [comment]
SQL_Connect also failed.

**Comment by kristiandz** [comment]
This is not a CoD4X/GSC hepldesk, those are basic errors, it clearly says that onRoundSwitch is undefined and that is stock code afaik, so there shouldn't be errors there unless you change something, then you are on your own. As for the sql it clearly says connection failed, so the information you provided is bad, or there is a problem on your machine.

PS. you leaked your SQL account ...

**Comment by gihanrangana** [comment]
> 

sql account is just for testing, for other programs sql is works fine no issues, i have nothing changed on your code just download and put it
