### ISSUE TITLE
Crnk error

### ISSUE THREAD

**Issue by ProGameCro** [kristiandz/ebc-pm#4]
throwing script exception: pair 'undefined' and 'MOD_SUICIDE' has unmatching types 'undefined' and 'string'

^1******* script runtime error *******
pair 'undefined' and 'MOD_SUICIDE' has unmatching types 'undefined' and 'string': (file 'maps/mp/gametypes/crnk.gsc', line 131)
 if(sMeansofDeath != "MOD_SUICIDE" && sMeansofDeath != "MOD_FALLING" && attacker != self)
                  *
^1called from:
(file 'maps/mp/gametypes/crnk.gsc', line 57)
 level.onPlayerKilled = onPlayerKilled();
                        *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 1969)
 [[level.onStartGameType]]();
         *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 24)
  [[level.callbackStartGameType]]();
          *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 20)
CodeCallback_StartGameType()
*
^1************************************
throwing script exception: cannot cast undefined to bool

**Comment by ProGameCro** [comment]
Hvala!

**Comment by kristiandz** [comment]
Commit [4758205](https://github.com/kristiandz/ebc-pm/commit/475820540fe222bec42fc45dd11cf8a755f8ee52)
