### ISSUE TITLE
request to commit config files

### ISSUE THREAD

**Issue by k4r3l01** [kristiandz/ebc-pm#6]
Hello thanks for this nice mod but its will be possible to commit configs to run this mod on our servers?
Thanks in advance sinceresly K4r3l01

**Comment by k4r3l01** [comment]
and please if its will be possible to upload sql structure for gsclib for this mod

**Comment by kristiandz** [comment]
Please read the readme fully, the only thing you need to run the server is the load the gsclib if you run the server on 1.8x and want sql support, that info is then found on gsclib which is linked from there.

As for the SQL structure, you can find it here on the b3 git for ebc: https://github.com/kristiandz/ebc-b3/blob/master/b3/sql/mysql/b3-update-ebc.sql
If you use that b3 it will be already applied on the first mysql start.

**Comment by k4r3l01** [comment]
ok thanks for your reply
