### ISSUE TITLE
Help with installing CGSC and gsclib to cod4x

### ISSUE THREAD

**Issue by k4r3l01** [kristiandz/ebc-pm#7]
Hello please its will be possible to help me how to install cgsc and gsclib im new in make and cmake is totally new for me untill now i used only sh to build plugins and i dont make any changes in make file.
Thanks in advance sinceresly K4r3l01
or if someone help me im on yours discord so so its wil be better to faster communication

**Comment by ProGameCro** [comment]
Send me your discord i will help you.

**Comment by k4r3l01** [comment]
thanks my discord name is same as my name on github

**Comment by k4r3l01** [comment]
thanks for try to help me but now i have builded cgsc and gsclib but strange is size of gsclib its over 7mb
