### ISSUE TITLE
_antiafk.gsc

### ISSUE THREAD

**Issue by yowisf** [kristiandz/ebc-pm#9]
Hello, how do I make the _antiafk.gsc script work? I placed it in my script folder and also added it to the thread promodcod\_antiafk::init(); correctly but it still keeps giving me an error, could you tell me where else I need to add something? Likewise, it could also help me to put an automatic autobalance script.

**Comment by kristiandz** [comment]
All the scripts work on the mod, I won't be supporting porting the scripts to a different mod, if you have issues with this mod as is, not working, post it, otherwise this is not a helpdesk.
